apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: node-observability-operator-agent
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - node-observability-agent
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - ""
  resources:
  - nodes/proxy
  verbs:
  - get
- nonResourceURLs:
  - /node-observability-status
  verbs:
  - get
- nonResourceURLs:
  - /node-observability-pprof
  - /node-observability-scripting
  verbs:
  - get
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
